PROFILE_DESCRIPTION="Full development stack"
PROFILE_CATALOGS=(
	terminal-base
	development-base
)
PROFILE_STEPS=(
	install_vscode
	install_java
	install_nodejs
	install_ruby
	install_dart
	install_git
)
PROFILE_APT_PACKAGES=(
	shellcheck
)
