# shellcheck shell=bash

readonly TERMINAL_TOOLS=(
  htop
  neofetch
  tree
  curl
  wget
  vim
  tmux
  net-tools
  build-essential
  fastfetch
  btop
  eza
  bat
  fzf
  ripgrep
)

readonly DEV_LANGUAGES_ALL=(
  python
  cpp
  java
  nodejs
  go
  rust
  ruby
  dart
)
